### ISSUE TITLE
Adding support for OpenAi custom assistants?

### ISSUE THREAD

**Issue by FarisZR** [Zaki-1052/GPTPortal#5] opened 2024-01-31 17:57 UTC
First, thanks for the great project!
It would be great if you could add support for the assistant API, which allows users to use the custom assistants they created on the dev platform.
Assistants unlike normal ChatGPT aren't just custom prompts, they can read files like CSVs, which can't be easily replicated with a system prompt.

https://platform.openai.com/docs/assistants/overview

**Comment by Zaki-1052** [comment] 2024-01-31 18:10
Thanks! I'm actually aware already, and while I'm a bigger proponent of the manual handling and embedding models if I can get them to work, the Assistants API Branch is [in progress](https://arc.net/l/quote/bobealvq) as mentioned in the [release](https://github.com/Zaki-1052/GPTPortal/releases/tag/v1.0.1). I've been busy with classes lately, but I intend to commit my changes this weekend once I add multiple file object handling for custom assistants. I'll update/create a branch and close the issue once I push the new version! Thanks for your feedback and the suggestion.

**Comment by Zaki-1052** [comment] 2024-02-03 03:05
I just pushed my changes to the new `assistants` branch. It retains the same functionality, though I removed some of the other models that don't apply, like Gemini and Vision, since the former seems unnecessary for this specific function and the latter doesn't work with the Assistants API. You can chat and select models as normal, and also upload files for GPT to access with its code interpreter. I did kind of want to figure out embeddings on my main branch, which I'll try to do this weekend, but if I'm too busy then I'll just make a new "Assistants Mode" on main and merge my relevant changes. There are still a few quality changes to make, and I need to ensure some other features like Voice Mode weren't broken, but I can confirm that the regular assistant creation and chat, along with file uploads, all work perfectly, as well as the export, which also ends the server. Will write some documentation before tomorrow. Hope you like it and the changes coming!

**Closed by Zaki-1052** 2024-02-03 03:05 UTC

**Comment by FarisZR** [comment] 2024-02-03 14:13
great! will tets it.

**Comment by FarisZR** [comment] 2024-02-03 21:07
Hey, can you give me more details about how to use this?
Where do I specify the assistant, do I have to get a special api key? Etc.
as the branch's readme is the same as main.

**Comment by Zaki-1052** [comment] 2024-02-03 21:27
Right, sorry, I forgot to do the documentation! The `.env` file is the same, just put your OpenAI key in the same format as the `.env.example` file. You don’t need to specify the assistant, though you can edit its instructions like before in `instructions.md`. Once you send the first message (or upload a file, whichever comes first), it creates the assistant with the system prompt and the model that’s selected (defaults to `gpt-4-turbo-preview); begins a thread, and adds your message to the thread. 

Then it starts a run, receding and displaying the response, and any subsequent messages you said will be added to the thread of the assistant created in the first message. You can continue to add files with the top-right file button, and it’ll be created for the assistant of that server instance. You can inspect the different assistants in your OpenAI dashboard, a new one is created when you start the server. I think that’s all; no special API Key or anything like that (pricing for code environment is purple on top of the model costs in usage). 

Let me know if I forgot anything; will put it in the ReadMe this afternoon!

**Comment by FarisZR** [comment] 2024-02-03 21:28
Great! 
but can i use an already existing assistant? or will it create a new assistant on every new chat?

**Comment by Zaki-1052** [comment] 2024-02-03 21:32
It’ll create a new Assistant on every new chat. You can go into the code and specify the ID if you like, for now they only persist across a single server instance. I can definitely add something later where you can choose from a previous one, though I don’t want to introduce too much database bloat or anything like that.

**Comment by FarisZR** [comment] 2024-02-03 21:33
it would be good enough if we can just specify the assistant ID to be used, it's displayed in the openai dashboard.

**Comment by Zaki-1052** [comment] 2024-02-03 21:37
Alright, thanks for the feedback! Will add a conditional then that takes the environment variable of the ID for the assistant, otherwise creates a new one; hopefully can push tonight!

**Comment by FarisZR** [comment] 2024-02-03 21:39
yup that would be great! since it will automatically import the prompt and any files and additional settings from openAI

**Comment by Zaki-1052** [comment] 2024-02-03 23:02
@FarisZR 
Hey! Since you're the one who asked, I thought I'd just get your quick feedback before I push the change and write the documentation to make sure I'm getting your desired functionality right! Basically, the new code will check if you have an Assistant ID stored in the `.env` file, and if there is one, then it will start a new thread (NOT continue the same conversation) but with the settings of that Assistant (custom instructions, model, and specified system message from when it was created). The code change is literally just that: 

```node.js
// Check if the Assistant ID is provided via .env and use it
  if (ASSISTANT_ID && !thread) {
    assistant = await openai.beta.assistants.retrieve(
      ASSISTANT_ID
    );
    thread = await openai.beta.threads.create();
    console.log("Using existing Assistant ID from .env, Thread ensured:", thread);
  } else if (!assistant || !thread) {
    // Create a new Assistant and Thread if not using an ID from .env
    assistant = await openai.beta.assistants.create({
```

So the terminal output would look like: 

zakiralibhai@My-MacBook-Air PortalTest % node server.js
Server running at http://localhost:3000
Initialize: true
Assistant and Thread ensured: {
  id: 'asst_DwaJp4C2hGmnCx6Amck7OedJ',
  object: 'assistant',
  created_at: 1707000885,
  name: 'Assistant',
  description: null,
  model: 'gpt-3.5-turbo',
  instructions: 'You are a helpful and intelligent AI assistant, knowledgeable about a wide range of topics and highly capable of a great many tasks.",
  tools: [ { type: 'code_interpreter' } ],
  file_ids: [],
  metadata: {}
} {
  id: 'thread_ylLE44suL9Vx0Yqm3Yj7ANL8',
  object: 'thread',
  created_at: 1707000885,
  metadata: {}
}
Run Status: in_progress
Run Status: completed
Response: Hello! How can I assist you today?
Try Response: { text: 'Hello! How can I assist you today?' }
^C
zakiralibhai@My-MacBook-Air PortalTest % node server.js
Server running at http://localhost:3000
Initialize: true
Using existing Assistant ID from .env, Thread ensured: {
  id: 'thread_bIgB6nBeo3zwCNjakev4ZjM2',
  object: 'thread',
  created_at: 1707000949,
  metadata: {}
}
Run Status: in_progress
Run Status: completed
Response: Hello! How can I assist you today?
Try Response: { text: 'Hello! How can I assist you today?' }
^C
zakiralibhai@My-MacBook-Air PortalTest % 

and in the `.env` file, I just had: 

> ASSISTANT_ID=asst_DwaJp4C2hGmnCx6Amck7OedJ

Is there anything else you're looking for with this feature? You have to know and input the ID before you run the server, otherwise it will just create a new Assistant per usual.

**Comment by FarisZR** [comment] 2024-02-03 23:57
Yup that should be it if it works with assistants created in the openai dashboard, do I have to supply the prompt locally or will it load the prompt, file IDs and other stuff automatically from openai?

-------- Ursprüngliche Nachricht --------
Am 04.02.24 00:02, schrieb Zaki-1052 - notifications at github.com :

**Comment by Zaki-1052** [comment] 2024-02-04 00:28
It'll all load automatically from OpenAI, you just need the ID of the Assistant/Thread and the prompt, files, etc. are all loaded from there. Haven't tested from the dashboard but worked when I created the Assistant in my command line. Just pushed, enjoy!

**Comment by FarisZR** [comment] 2024-02-04 15:19
Hey, it seems you changed something and the program now listens only to [::1]:3000, this wouldn't work in docker, it needs to listen on 0.0.0.0:3000.
